### ISSUE TITLE
Dispatching Interface

### ISSUE THREAD

**Issue by mcdeoliveira** [EMSTrack/WebServerAndClient#43]
1. Move drop pin with double click
2. Make sure last name goes with the dispatching message
3. Make sure address failure does not impede dispatching
4. Dynamically update the ambulance tab and status
5. Test dispatching after a error, e.g. street address failure. Leon reports that street address gets fixed but the ambulance been dispatched is compromised

**Comment by Deeeeen** [comment]
No 2 has been solved
